### ISSUE TITLE
Environment set up guidance needed

### ISSUE THREAD

**Issue by Opdoop** [AI-secure/SemAttack#1]
Thanks for releasing this project. What are the dependency packages? A `requirements.txt` or `environment.yml` is welcome.

**Comment by Opdoop** [comment]
Also, guidance on dataset construction is needed. Directly providing these dependent resources are welcome.
https://github.com/AI-secure/SemAttack/blob/00b77bd043d0f0e8b2067ff9ccb99b50f6be0fc5/English/bert/util.py#L97-L108

**Comment by garyxcj** [comment]
Hi,

Thanks for your interest in our work.

We have updated our README and provided requirements and the preprocessed dataset. Please let me know if you have further questions.
