### ISSUE TITLE
Confusion of Embedding Space Construction

### ISSUE THREAD

**Issue by Opdoop** [AI-secure/SemAttack#2]
The released embedding is called `yelp.pkl` and described as `We also provide processed dataset with embedding space`. This seems the embedding is dataset-related. On the contrary, according to Appendix `D.2 Embedding Space Construction` in the paper, the embedding should be dataset independent. So this disagreement makes me confused. 
My questions are:
1. Is the embedding dataset independent or not?
2. If it's dataset independent, could we use the embedding `yelp.pkl` for other English datasets like `sst-2`/`IMDB`, etc?
3. If it's dataset-related, could you provide this embedding construction script?

Thanks in advance~

**Comment by garyxcj** [comment]
Hi, sorry for the confusion. The released dataset contains synonyms obtained by querying the embedding space,  but not the whole embedding space. We have updated the README to make it more clear. Here are the answers to your questions.

1. The embedding space is dataset independent.
2. `yelp.pkl` is the processed Yelp dataset, which includes the original Yelp dataset and synonyms returned by different semantic perturbation functions. We can not use it for other English datasets.
3. The embedding construction is done following the instructions in [this repository](https://github.com/PAIR-code/interpretability).

Please let me know if you have further questions.
