### ISSUE TITLE
Releasing Semantic Perturbation Functions Construction needed

### ISSUE THREAD

**Issue by Opdoop** [AI-secure/SemAttack#3]
Correct me if I'm wrong. It seems like the current code only has the `2.3 Attack Algorithm SemAttack` part that searches for the optimal perturbations from different semantic spaces. According to the paper: 
> We propose a **unified** and effective adversarial attack framework SemAttack by **constructing semantic perturbation functions**, which constraint perturbations within different semantic spaces and their combinations.

Please release the `Semantic Perturbation Functions Construction` part, so that we could use SemAttack other than the provided `Yelp` https://github.com/AI-secure/SemAttack/issues/2#issuecomment-1136615041. The current version is useless other than running the demo.
It is good to see the full functional API that we could use SemAttack to test the robustness of any target model with any dataset.

**Comment by Opdoop** [comment]
I am aware that embedding construction is dependent on [this repository](https://github.com/PAIR-code/interpretability). But only releasing `2.3` code makes the current version of SemAttack only a toy, not a tool.

**Comment by garyxcj** [comment]
Hi,

Thanks for your interest in our work!

We have released the code for semantic perturbation functions. Please let me know if you have further questions.

**Comment by Opdoop** [comment]
❤Thanks for your response! I'll take a look later! This is exciting!
