### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by ArJone-cyh** [AI-secure/SemAttack#4]
当我运行English/bert/trian.py 时 出现以下报错 FileNotFoundError: [Errno 2] No such file or directory: 'full-trn-processed.pkl'
这是否意味着 该pkl 还未公开呢 
![image](https://user-images.githubusercontent.com/65947359/203547084-494acdda-069b-4fa5-add9-fc1062ca7ee6.png)

**Comment by boxin-wbx** [comment]
我们提供了 Yelp dataset for the development and debugging purpose，请参见 https://drive.google.com/drive/folders/1nZzqaqJIhO75pkTK_AxJVzGY0uLxMJ6O
