### ISSUE TITLE
get_FC problem

### ISSUE THREAD

**Issue by Fangjjjjj** [AI-secure/SemAttack#5]
您好，可以请问一下Contextualized的扰动空间具体是如何进行构建的吗？文件中没有包含contextualized embedding文件，给的链接（["Visualizing and Measuring the Geometry of BERT"]）里面的代码生成的是2维的embedding，和提示中说到的N*768不太一样。

Could you help me to figure out how to construct BERT embedding space? After I followed the work in github（["Visualizing and Measuring the Geometry of BERT"]）, I only got 2D embedding representations for each word and in separate files, which is different from the description of an N * 768 tensor.

**Comment by boxin-wbx** [comment]
We follow this paper https://arxiv.org/abs/1906.02715 to get the contextualized embeddings. Please refer to their method or codebase for more details.
